### ISSUE TITLE
Use binary search rather than incremental

### ISSUE THREAD

**Issue by spacelama** [b3n-j4m1n/salary-seeker#1]
This takes quite a few calls to the website, in which case you could find yourself afoul of their website filter.

So to minimise the number of calls to the website,

1) Find a minimum by choosing an arbitrary number (eg, 100,000).

2.a.i) If minimum must be lower than that, half minimum.

2.b.i) Or if minimum is higher, and first iteration, keep doubling minimum until find value where minimum must be lower, and go back to step 1

2.b.ii) Or if minimum is greater than this value, and not the first iteration, then find minimum between the two bounds you've previously set, and go back to step 1

3) Equivalent for maximum is an excercise left to the reader, but I'd start at twice the just-determined minimum

This will converge in O(log(N)) time rather than O(N).

**Comment by b3n-j4m1n** [comment]
updated, much faster now
