### ISSUE TITLE
Turn this into an API

### ISSUE THREAD

**Issue by DeeplyDiligent** [b3n-j4m1n/salary-seeker#2]
Use heroku, aws or azure and turn this into an API. This way we can make it into a chrome extension running on any computer!

**Comment by thisistony** [comment]
I'm in the process of making this at the moment!

**Comment by b3n-j4m1n** [comment]
There's a chrome extension here - https://chrome.google.com/webstore/detail/salary-seeker/okapllpgbpdbfbpaelpjpgdmholakcfm

I didn't make it and won't be supporting it though.
