### ISSUE TITLE
All Jobs show as 30k, No Job Title

### ISSUE THREAD

**Issue by stephendt** [b3n-j4m1n/salary-seeker#5]
As per the title - try a few different job posts and they all show up with no title and a pay bracket of 30,000 to 30,001, which certainly cannot be correct. Any ideas on what might be causing this?

![Screenshot at 2019-11-28 20-47-28](https://user-images.githubusercontent.com/13553887/69800136-5a368f80-1220-11ea-918d-2a0cf402ab73.png)

**Comment by b3n-j4m1n** [comment]
fixed, api changed to https://jobsearch-api.cloud.seek.com.au
